plugin:
  enabled: true
throw-velocity:
  current: 1.5
give-time:
  current: 5
cooldown:
  current: 3
direct-hit-velocity:
  current: 3
direct-hit-damage:
  current: 6
water-damage:
  current: 3
countdown:
  current: 5
startingItems:
  - ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: RED_STAINED_GLASS_PANE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §cTNT
      lore:
        - TNT will always go in the first slot.
  - ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: SCAFFOLDING
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: SCAFFOLDING
    amount: 64
  - ==: org.bukkit.inventory.ItemStack
    v: 2567
    type: ENDER_PEARL
    amount: 3
  - null
  - null
  - null
  - null
  - null