plugin:
  enabled:
throw-velocity:
  default: 1.5
  current: 1.5
give-time:
  default: 5
  current: 5
cooldown:
  default: 3
  current: 3
direct-hit-velocity:
  default: 3
  current: 3
direct-hit-damage:
  default: 6
  current: 6
water-damage:
  default: 3
  current: 3
countdown:
  default: 5
  current: 5